name: All

defaults:
  run:
    shell: bash

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  python-unittest:
    strategy:
      matrix:
        pythonversion: ["3.8","3.9","3.10"]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tests
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.pythonversion }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.pythonversion }}
    - name: Install dependencies
      run: |
        sudo apt-get install make gcc g++ ghdl-llvm
        python -m pip install --upgrade pip
        pip install pytest
        pip install ..
    - name: Python unittest
      run: |
        pytest

  #python-mypy:
  #  runs-on: ubuntu-latest
  #  steps:
  #  - uses: actions/checkout@v2
  #  - name: Set up Python 3.9
  #    uses: actions/setup-python@v2
  #    with:
  #      python-version: 3.9
  #  - name: Install dependencies
  #    run: |
  #      python -m pip install --upgrade pip
  #      pip install mypy
  #      pip install .
  #  - name: Static Analysis with mypy
  #    run: |
  #      mypy cocotbnumpy tests
